version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=sqlite:///instance/agency_sales.db
    volumes:
      - .:/app:rw
    restart: unless-stopped
